name: Setup with Node
description: Perform standard setup and install dependencies using npm.
inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 24.x

runs:
  using: composite
  steps:
      - name: Set Node.js (${{ inputs.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.com

      - name: Install dependencies
        shell: bash
        run: npm install --frozen-lockfile --silent