/**
 * The one place a page is registered: routes.ts and nav.config.ts are both
 * derived from this list, in this order. An empty routePath is the site index.
 */
export const contentPages = [
  {
    section: "Introduction",
    label: "Installation",
    href: "/",
    routePath: "",
    contentPath: "content/index.mdx",
  },
  {
    section: "Introduction",
    label: "Getting Started",
    href: "/getting-started",
    routePath: "getting-started",
    contentPath: "content/getting-started.mdx",
  },
  {
    section: "Introduction",
    label: "FAQ",
    href: "/faq",
    routePath: "faq",
    contentPath: "content/faq.mdx",
  },
  {
    section: "Guides",
    label: "Accessibility",
    href: "/guides/accessibility",
    routePath: "guides/accessibility",
    contentPath: "content/guides/accessibility.mdx",
  },
  {
    section: "Guides",
    label: "Annotations",
    href: "/guides/annotations",
    routePath: "guides/annotations",
    contentPath: "content/guides/annotations.mdx",
  },
  {
    section: "Guides",
    label: "Axes",
    href: "/guides/axes",
    routePath: "guides/axes",
    contentPath: "content/guides/axes.mdx",
  },
  {
    section: "Guides",
    label: "Behaviors",
    href: "/guides/behaviors",
    routePath: "guides/behaviors",
    contentPath: "content/guides/behaviors.mdx",
  },
  {
    section: "Guides",
    label: "Breakpoints",
    href: "/guides/breakpoints",
    routePath: "guides/breakpoints",
    contentPath: "content/guides/breakpoints.mdx",
  },
  {
    section: "Guides",
    label: "Colors",
    href: "/guides/colors",
    routePath: "guides/colors",
    contentPath: "content/guides/colors.mdx",
  },
  {
    section: "Guides",
    label: "Controls",
    href: "/guides/controls",
    routePath: "guides/controls",
    contentPath: "content/guides/controls.mdx",
  },
  {
    section: "Guides",
    label: "Formatting",
    href: "/guides/formats",
    routePath: "guides/formats",
    contentPath: "content/guides/formats.mdx",
  },
  {
    section: "Guides",
    label: "Legends",
    href: "/guides/legends",
    routePath: "guides/legends",
    contentPath: "content/guides/legends.mdx",
  },
  {
    section: "Guides",
    label: "Tooltips",
    href: "/guides/tooltips",
    routePath: "guides/tooltips",
    contentPath: "content/guides/tooltips.mdx",
  },
  {
    section: "Layout",
    label: "Small Multiples",
    href: "/layout/small-multiples",
    routePath: "layout/small-multiples",
    contentPath: "content/layout/small-multiples.mdx",
  },
  {
    section: "Charts",
    label: "Area chart",
    href: "/area-chart-stacked",
    routePath: "area-chart-stacked",
    contentPath: "content/charts/area-chart-stacked.mdx",
  },
  {
    section: "Charts",
    label: "Bar chart (vertical)",
    href: "/bar-chart-vertical",
    routePath: "bar-chart-vertical",
    contentPath: "content/charts/bar-chart-vertical.mdx",
  },
  {
    section: "Charts",
    label: "Bar chart (vertical, stacked)",
    href: "/bar-chart-vertical-stacked",
    routePath: "bar-chart-vertical-stacked",
    contentPath: "content/charts/bar-chart-vertical-stacked.mdx",
  },
  {
    section: "Charts",
    label: "Bar chart (vertical, nested)",
    href: "/bar-chart-vertical-nested",
    routePath: "bar-chart-vertical-nested",
    contentPath: "content/charts/bar-chart-vertical-nested.mdx",
  },
  {
    section: "Charts",
    label: "Bar chart (vertical, grouped)",
    href: "/bar-chart-vertical-grouped",
    routePath: "bar-chart-vertical-grouped",
    contentPath: "content/charts/bar-chart-vertical-grouped.mdx",
  },
  {
    section: "Charts",
    label: "Bar chart (horizontal)",
    href: "/bar-chart-horizontal",
    routePath: "bar-chart-horizontal",
    contentPath: "content/charts/bar-chart-horizontal.mdx",
  },
  {
    section: "Charts",
    label: "Bar chart (horizontal, stacked)",
    href: "/bar-chart-horizontal-stacked",
    routePath: "bar-chart-horizontal-stacked",
    contentPath: "content/charts/bar-chart-horizontal-stacked.mdx",
  },
  {
    section: "Charts",
    label: "Bar chart (horizontal, grouped)",
    href: "/bar-chart-horizontal-grouped",
    routePath: "bar-chart-horizontal-grouped",
    contentPath: "content/charts/bar-chart-horizontal-grouped.mdx",
  },
  {
    section: "Charts",
    label: "Line chart",
    href: "/line-chart",
    routePath: "line-chart",
    contentPath: "content/charts/line-chart.mdx",
  },
  {
    section: "Charts",
    label: "Heat table",
    href: "/heat-table",
    routePath: "heat-table",
    contentPath: "content/charts/heat-table.mdx",
  },
  {
    section: "Charts",
    label: "Pack",
    href: "/pack",
    routePath: "pack",
    contentPath: "content/charts/pack.mdx",
  },
  {
    section: "Charts",
    label: "Sunburst",
    href: "/sunburst",
    routePath: "sunburst",
    contentPath: "content/charts/sunburst.mdx",
  },
  {
    section: "Charts",
    label: "Treemap",
    href: "/treemap",
    routePath: "treemap",
    contentPath: "content/charts/treemap.mdx",
  },
  {
    section: "Charts",
    label: "Choropleth maps",
    href: "/map-standard",
    routePath: "map-standard",
    contentPath: "content/charts/map-standard.mdx",
  },
  {
    section: "Charts",
    label: "Extended maps",
    href: "/map-extended",
    routePath: "map-extended",
    contentPath: "content/charts/map-extended.mdx",
  },
  {
    section: "Charts",
    label: "Signature maps",
    href: "/map-signature",
    routePath: "map-signature",
    contentPath: "content/charts/map-signature.mdx",
  },
  {
    section: "Charts",
    label: "Pie chart",
    href: "/pie-charts",
    routePath: "pie-charts",
    contentPath: "content/charts/pie-charts.mdx",
  },
  {
    section: "Charts",
    label: "Population pyramid",
    href: "/population-pyramid",
    routePath: "population-pyramid",
    contentPath: "content/charts/population-pyramid.mdx",
  },
  {
    section: "Charts",
    label: "Sankey diagram",
    href: "/sankey",
    routePath: "sankey",
    contentPath: "content/charts/sankey.mdx",
  },
  {
    section: "Charts",
    label: "Scatterplot",
    href: "/scatterplot",
    routePath: "scatterplot",
    contentPath: "content/charts/scatterplot.mdx",
  },
  {
    section: "Charts",
    label: "Scatterplot over time",
    href: "/scatterplot-over-time",
    routePath: "scatterplot-over-time",
    contentPath: "content/charts/scatterplot-over-time.mdx",
  },
] as const;
