name: Publish to NPM
on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9].*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/setup

      - run: pnpm run check
      - run: pnpm run type-check
      - run: pnpm --filter sszvis exec playwright install --with-deps
      - run: pnpm run test:unit
      - run: pnpm run build

      - name: Publish sszvis
        run: pnpm publish --access public --no-git-checks
        working-directory: packages/sszvis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
