name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-testing:
    name: "Unit Testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main

      - run: |
          nix develop --command bash -c \
            'npm install --frozen-lockfile'

      - run: |
          nix develop --command bash -c \
            'npm run test:unit'

  snapshot-testing:
    name: "Snapshot Testing"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main

      - run: |
          nix develop --command bash -c \
            'npm install --frozen-lockfile'

      - run: |
          nix develop --command bash -c \
            'npm run build'

      - name: Serve docs and run tests
        run: |
          nix develop --command bash -c \  
             'npx concurrently -k -s first -n "DOC,TEST" -c "magenta,blue" \
                "npm run start" \
                "npx wait-on http://localhost:8000 && npm run test:snapshot"'
