name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snapshot-testing:
    name: "Snapshot Testing"
    timeout-minutes: 60
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build Docs
        run: npm run build

      - name: Serve docs and run tests
        run: |
          npx concurrently -k -s first -n "DOC,TEST" -c "magenta,blue" \
            "npm run start" \
            "npx wait-on tcp:127.0.0.1:8000 && npm run test:snapshot"
