name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: false
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: nicknovitski/nix-develop@v1

      - run: npm install --frozen-lockfile

      - run: npm run test:lint
