name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: false
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - run: |
          nix develop --command bash -c \
            'npm install --frozen-lockfile'

      - run: |
          nix develop --command bash -c \
            'npm test:lint'
